# Get started with PyTorch 

## To Use PyTorch, use `import torch`

In [1]:
import torch 

## In `torch`, we are mostly going to use these modules: 
    1. torch.nn 
    2. torch.optim 

In [2]:
# In the beginning, we are going to import these modules like 

import torch.nn as nn 
import torch.optim as optim

### torch.nn        :- Used mostly for Building the Neural Network model
### torch.optim  :- Used to initializing the Optimizer

## Now let's look at torch.Tensors

torch.Tensor is a `multi-dimensional` matrix containing `single data type` elemets 
#### Default tensor type : `torch.FloatTensor`

In [7]:
x = torch.tensor([2.0, 3.0, 4.0])

print("x: ", x)
print(x.shape)

x:  tensor([2., 3., 4.])
torch.Size([3])


In [11]:
x = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

print("x: ", x)
print(x.shape)

x:  tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [17]:
# We can also have Scalars in torch.Tensor

s = torch.tensor(4.5)
print(s)

# To get only the value of the Scalar 
print(s.item())

tensor(4.5000)
4.5


## Differentiation using Torch 

### To enable automatic differentiation, we can use a parameter `requires_grad = True` 

### In the example below, our function is $x^2$

### We differentiate it to obtain $2x$

In [27]:
x = torch.tensor([4.0, 5.0], requires_grad = True)
print("TENSOR:                ", x)
out = x.pow(2).sum()
print("OUT:                   ", out)
out.backward()
print("After Differentiation: ", x.grad)  # Calculated Gradients

TENSOR:                 tensor([4., 5.], requires_grad=True)
OUT:                    tensor(41., grad_fn=<SumBackward0>)
After Differentiation:  tensor([ 8., 10.])


# Sending our Data to GPU 

## In PyTorch, we can send our Data to GPU. 
    **Make sure your GPU is CUDA Enabled**

In [30]:
print(x)

# Send this tensor to GPU 

x = x.cuda()

print(x)

tensor([4., 5.], requires_grad=True)
tensor([4., 5.], device='cuda:0', grad_fn=<ToCopyBackward0>)


## We can send our Tensors to CUDA in multiple ways

1. x.cuda() 
2. x.to(torch.device("cuda:0"))
3. tensor([1., 2., 3.], device = torch.device("cuda:0"))

## Now we can bring back our Tensors from CUDA to CPU 

In [36]:
# Bring Tensor to CPU 
print("To CPU:                        : ", x.cpu())
print("To CPU and Remove required_grad: ", x.cpu().detach())
print("Also convert to Numpy array    : ", x.cpu().detach().numpy())

To CPU:                        :  tensor([4., 5.], grad_fn=<ToCopyBackward0>)
To CPU and Remove required_grad:  tensor([4., 5.])
Also convert to Numpy array    :  [4. 5.]


## Convert Numpy Array to Torch Tensor

In [43]:
import numpy as np 

a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

In [44]:
t = torch.tensor(a)
t

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

## Change shape of a Tensor
### We use `tensor.view(*shape)` to change the shape 

In [49]:
print(t)
print(t.view((1, 4)))
print(t.view((4, 1)))
print(t.view(-1))

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1., 1.]], dtype=torch.float64)
tensor([[1.],
        [1.],
        [1.],
        [1.]], dtype=torch.float64)
tensor([1., 1., 1., 1.], dtype=torch.float64)


## There are many more Tensor Ops avaliable 

Check: https://pytorch.org/docs/stable/tensors.html 

### Remember : Most ops are similar to numpy and other scientific libraries 